ci: run tests even after failure of one sute for other suites to complete

diff --git a/.github/workflows/desktop-linux-test-pull.yml b/.github/workflows/desktop-linux-test-pull.yml
--- a/.github/workflows/desktop-linux-test-pull.yml
+++ b/.github/workflows/desktop-linux-test-pull.yml
@@ -58,6 +58,8 @@ jobs:
 
       - name: Run tauri unit tests
         uses: nick-fields/retry@v3
+        id: linuxRunUnit
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -65,6 +67,8 @@ jobs:
 
       - name: Run tauri integration tests
         uses: nick-fields/retry@v3
+        id: linuxRunIntegration
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -72,6 +76,8 @@ jobs:
 
       - name: Run tauri mainview tests
         uses: nick-fields/retry@v3
+        id: linuxRunMainview
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -79,6 +85,8 @@ jobs:
 
       - name: Run tauri livepreview tests
         uses: nick-fields/retry@v3
+        id: linuxRunLivepreview
+        continue-on-error: true
         with:
           timeout_minutes: 12
           max_attempts: 3
@@ -86,7 +94,31 @@ jobs:
 
       - name: Run tauri LegacyInteg tests
         uses: nick-fields/retry@v3
+        id: linuxRunLegacyInteg
+        continue-on-error: true
         with:
           timeout_minutes: 20
           max_attempts: 3
           command: xvfb-run ./src-tauri/target/debug/phoenix-test --run-tests=LegacyInteg -q
+
+      - name: Fail on test runs failed in Linux
+        if: steps.linuxRunUnit.outcome == 'failure' || steps.linuxRunIntegration.outcome == 'failure' || steps.linuxRunMainview.outcome == 'failure' || steps.linuxRunLivepreview.outcome == 'failure' || steps.linuxRunLegacyInteg.outcome == 'failure'
+        run: |
+          echo "Linux tests failed, marking step as failed"
+          echo "Failed tests:"
+          if [ "${{ steps.linuxRunUnit.outcome }}" == "failure" ]; then
+            echo "- Run tauri unit tests"
+          fi
+          if [ "${{ steps.linuxRunIntegration.outcome }}" == "failure" ]; then
+            echo "- Run tauri integration tests"
+          fi
+          if [ "${{ steps.linuxRunMainview.outcome }}" == "failure" ]; then
+            echo "- Run tauri mainview tests"
+          fi
+          if [ "${{ steps.linuxRunLivepreview.outcome }}" == "failure" ]; then
+            echo "- Run tauri livepreview tests"
+          fi
+          if [ "${{ steps.linuxRunLegacyInteg.outcome }}" == "failure" ]; then
+            echo "- Run tauri LegacyInteg tests"
+          fi
+          exit 1
